### PR TITLE
AlarmManager.cancel on null intent will throw when targeting N

### PR DESCRIPTION
**Pull request by N-Pex**

### CODE REVIEW

**Comment by eighthave** [comment]
When `mTimeoutIntent` is null, does that mean that the alarm has already
been canceled?  This change might just mean that under certain
conditions, it is not possible to cancel/reset the timeout.

**Comment by N-Pex** [comment]
Nope, it being null is that startTimer has never been called. It does not change any logic here, it's just that it has become illegal to call cancel() with null.

**Comment by n8fr8** [comment]
I saw this same issue with Zom when I switched to target 25... in the Android before N, they just log the error and allow it to pass. With N, they now cancel it and get a NPE.

**Comment by eighthave** [comment]
so you're saying that AlarmManager.cancel() no longer handles nulls?

**Comment by N-Pex** [comment]
@eighthave Exactly. Please see docs here: https://developer.android.com/reference/android/app/AlarmManager.html#cancel(android.app.PendingIntent) "This parameter must not be null."

**Pull request merged**
