### PR TITLE
Reproducible Gradle build process

### PR DESCRIPTION
**Pull request by str4d**
This PR contains a Gradle build process that generates Android libraries for both `cachewordlib` and `cachewordhelpers` with verified dependencies, a script to enable reproducible builds, and support for uploading the libraries to Maven Central.

I can drop the `cachewordhelpers` build script if desired, as I was told it will likely just be example code.

If uploading to Bintray's JCenter is preferred, I can set that up instead. JCenter syncs packages from Maven Central (and `jcenter()` is now the default for Android Studio), but I believe it also has the ability to make uploading packages from JCenter to Maven Central trivial (to support users that use the `mavenCentral()` repository instead of `jcenter()`).

### CODE REVIEW

**Comment by eighthave** [comment]
wow, looks like you covered the whole shebang :)  any tips on how to verify the `gradle-witness.jar`?

**Comment by str4d** [comment]
It's the same one I built for https://github.com/i2p/i2p.android.base from the latest gradle-witness source. But I could write a script for making it reproducibly (and make a PR with the repo for others to use it).

**Comment by str4d** [comment]
Hmm, I tried migrating the make-gradle-build but it seems that faketime is not sufficient. Using plain `gradle build` two times, two Java classes in the jars each differ in size by two bytes; with faketime, the size differences are reduced to one byte.

`gradle-witness` is written in Groovy, and [supposedly it can be compiled without timestamps](https://github.com/groovy/groovy-core/pull/499), but I'm not sure how to do this yet.

**Comment by str4d** [comment]
As noted on [the mailing list](https://lists.mayfirst.org/pipermail/guardian-dev/2015-April/004380.html), if gradle/gradle#448 is accepted then the Gradle wrapper can be re-introduced by including the SHA-256 hash of the downloaded Gradle distribution, [like this](https://github.com/open-keychain/open-keychain/commit/41968206d3deed789dd5b35468a8d8487755234c).

**Comment by str4d** [comment]
On second thought, that PR only fixes `<_hc> downloading and executing code from unverified sources?`. It doesn't resolve `<_hc> even worse, it does not even enforce HTTPS`, but maybe that is not as much of an issue if `gradle-wrapper.jar` is verifying hashes?

Also left unresolved is `<_hc> and also includes unverified jars in your project`, but that could be solved by making `gradle-wrapper.jar` reproducible.

**Comment by eighthave** [comment]
Enforcing HTTPS is not a big deal if there is something reliably verifying the
jars that are downloaded.  Using gradle-witness with a build.gradle that is
committed to git would be one reliable way to verify that the jar has not
changed since the original committer saw it.  Unfortunately, that does not
verify that the jar is the same as the one the original creator made.

Even with that pull request merged into gradle, I still think that
gradle-wrapper has too many security issues for it to be included.  Instead,
my plan is to get gradle packaged up well and as widely as possible to
leverage the existing reliable methods for distributing software.  For more info:

https://guardianproject.info/2015/04/30/getting-android-tools-into-debian/

**Comment by eighthave** [comment]
Since there already is basic gradle support in cacheword, I'm closing this.

**Pull request closed without merging**
